define([
	"./Normal",
	"./Effect",
	"./Ritual",
	"./Fusion",
	"./Synchro",
	"./Xyz",
	"./Link",
	"./Token",
	"./Spell",
	"./Trap",
	"./Skill",
	// "./DarkSynchro",
	// "./Epoch",
	// "./Warp",
	// "./Unity",
	// "./Rainbow",
],
function ygo_template_all(Normal, Effect, Ritual, Fusion, Synchro, Xyz, Link, Token, Spell, Trap, Skill)
{
	return {
		Normal: { value: "Normal", fn: Normal },
		Effect: { value: "Effect", fn: Effect },
		Ritual: { value: "Ritual", fn: Ritual },
		Fusion: { value: "Fusion", fn: Fusion },
		Synchro: { value: "Synchro", fn: Synchro },
        Xyz: { value: "Xyz", fn: Xyz },
		Link: { value: "Link", fn: Link },
		Token: { value: "Token", fn: Token },
		Spell: { value: "Spell", fn: Spell },
		Trap: { value: "Trap", fn: Trap },
		Skill: { value: "Skill", fn: Skill },
		// DarkSynchro: { value: "DarkSynchro", name: "Dark Synchro", fn: DarkSynchro },
		// Epoch: { value: "Epoch", name: "Bigbang", fn: Epoch },
		// Warp: { value: "Warp", name: "Time Leap", fn: Warp },
		// Unity: { value: "Unity", fn: Unity },
		// Rainbow: { value: "Rainbow", fn: Rainbow },
	};
});
